11.1.out: 11.1.fs
	fsharpi --readline -r /home/csp/lib/fsharppower/bin/FSharp.PowerPack.dll < 11.1.fs > 11.1.out

11.2.out: 11.2.fs
	fsharpi --readline -r /home/csp/lib/fsharppower/bin/FSharp.PowerPack.dll < 11.2.fs > 11.2.out

11.3.out: 11.3.fs
	fsharpi --readline -r /home/csp/lib/fsharppower/bin/FSharp.PowerPack.dll < 11.3.fs > 11.3.out

11.4.out: 11.4.fs
	fsharpi --readline -r /home/csp/lib/fsharppower/bin/FSharp.PowerPack.dll < 11.4.fs > 11.4.out

11.8.out: 11.8.fs Cont/Icon.fs
	fsharpi --readline -r /home/csp/lib/fsharppower/bin/FSharp.PowerPack.dll Cont/Icon.fs < 11.8.fs > 11.8.out
